## Data Science Bootcamp
### Week 2: Introduction to Numpy and Pandas

- **Questions 1 - 2**: Based on the email with title "Data Science Bootcamp Week 2 Follow Up" (receive on Fri, Mar 7, 5:01 PM)
- Submitted via gitHub and Google doc

# Part 1 - Numpy

In [1]:
# use this dataset for the first 4 questions
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

In [3]:
import numpy as np
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

## Part 1 - Question 1

⁠Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [3]:
# import numpy library as np
import numpy as np

In [70]:
# define two custom numpy arrays, A and B
A = np.array([[4,5,6], [7,8,9]])
B = np.array([[1,2,3], [4,5,6]])

In [71]:
# testing
print(f"Matrix A:\n{A}\n")
print(f"Matrix B:\n{B}")

Matrix A:
[[4 5 6]
 [7 8 9]]

Matrix B:
[[1 2 3]
 [4 5 6]]


In [72]:
# stack A and B vertically using np.vstack
vertical_stack_array = np.vstack((A,B))

In [73]:
# testing
print(f"vertically stacked array: \n{vertical_stack_array}")

vertically stacked array: 
[[4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]]


In [74]:
# stack A and B horizontally using np.hstack
horizontal_stack_array = np.hstack((A,B))

In [75]:
# testing
print(f"horizontally stacked array: \n{horizontal_stack_array}")

horizontally stacked array: 
[[4 5 6 1 2 3]
 [7 8 9 4 5 6]]


## Question 1-2.⁠ 
⁠Find common elements between A and B. [Hint : Intersection of two sets]**

In [76]:
# flatten arrays
A_flatten = A.flatten()
B_flatten = B.flatten()

In [77]:
print(f"Elements of matrix A: {A_flatten}")
print(f"Structure of A_flatten: {type(A_flatten)}\n")  

print(f"Elements of matrix B: {B_flatten}")
print(f"Structure of B_flatten: {type(B_flatten)}\n")  

Elements of matrix A: [4 5 6 7 8 9]
Structure of A_flatten: <class 'numpy.ndarray'>

Elements of matrix B: [1 2 3 4 5 6]
Structure of B_flatten: <class 'numpy.ndarray'>



In [78]:
# change to sets
A_set = set(A_flatten)
B_set = set(B_flatten)

In [79]:
print(f"Set A: {A_set}")
print(f"Set B: {B_set}")

Set A: {4, 5, 6, 7, 8, 9}
Set B: {1, 2, 3, 4, 5, 6}


In [80]:
# Use A.intersection(B)
A_set.intersection(B_set)

{4, 5, 6}

## Question 1-3⁠ 
⁠Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [83]:
A_set_array = np.array(list(A_set))
extract_indices = np.where((A_set_array > 5) & (A_set_array < 10))

In [89]:
print(f"Extracted numpy unit: {extract_indices}")

Extracted numpy unit: (array([2, 3, 4, 5], dtype=int64),)


In [85]:
extract_values = A_set_array[(A_set_array > 5) & (A_set_array < 10)]

In [88]:
print(f"Values: {extract_values}")

Values: [6 7 8 9]


## Question 1-4. 
⁠Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [91]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [92]:
print(iris_2d)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [96]:
# Filter the rows of iris_2d such that has petallength (3rd column) > 1.5
print(iris_2d[iris_2d[:, 2] > 1.5])

[[5.4 3.9 1.7 0.4]
 [4.8 3.4 1.6 0.2]
 [5.7 3.8 1.7 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [5.1 3.8 1.6 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.

In [95]:
# Filter the rows of iris_2d such that the 1st column has < 5.0
print(iris_2d[iris_2d[:, 0] < 5.0])

[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [4.6 3.4 1.4 0.3]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [4.6 3.6 1.  0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 3.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [4.8 3.  1.4 0.3]
 [4.6 3.2 1.4 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [101]:
# 3rd column > 1.5 and 1st column < 5
iris_2d_filtered = iris_2d[(iris_2d[:,2] > 1.5) & (iris_2d[:,0] < 5.0)]
print(iris_2d_filtered)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


# Pandas

**Question 2- 1**.⁠ ⁠From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

In [106]:
# import panads
import pandas as pd

# load a data frame
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [107]:
df_filtered_question1 = df[["Manufacturer", "Model", "Type"]]

In [109]:
df_filtered_question1

Manufacturer    Model     Type
0         Acura  Integra    Small
1           NaN   Legend  Midsize
2          Audi       90  Compact
3          Audi      100  Midsize
4           BMW     535i  Midsize
..          ...      ...      ...
88   Volkswagen  Eurovan      Van
89   Volkswagen   Passat  Compact
90   Volkswagen  Corrado   Sporty
91        Volvo      240  Compact
92          NaN      850  Midsize

[93 rows x 3 columns]

In [110]:
df_filtered_question1[::20] # display every 20 element

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

## Answer to 2-1

In [111]:
df_question1 = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df_question1_filtered = df_question1[["Manufacturer", "Model", "Type"]][::20]
df_question1_filtered

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

## Question 1-2.⁠ 
⁠Replace missing values in Min.Price and Max.Price columns with their respective mean.

In [113]:
df_question2 = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [114]:
# take a look of this data frame
df_question2.head()

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [115]:
df_question2[["Min.Price", "Max.Price"]]

Min.Price  Max.Price
0        12.9       18.8
1        29.2       38.7
2        25.9       32.3
3         NaN       44.6
4         NaN        NaN
..        ...        ...
88       16.6       22.7
89       17.6       22.4
90       22.9       23.7
91       21.8       23.5
92       24.8       28.5

[93 rows x 2 columns]

In [117]:
# calculate the mean of min.Price and the mean of max.Price
min_price_column_mean = df_question2["Min.Price"].mean()
max_price_column_mean = df_question2["Max.Price"].mean()

print(f"mean of min_price column: {min_price_column_mean}")
print(f"mean of max_price column: {max_price_column_mean}")

mean of min_price column: 17.118604651162787
mean of max_price column: 21.45909090909091


In [118]:
# check a nan value
df_question2["Min.Price"][3]

nan

In [121]:
# check the values of nan in min.Price
df_question2["Min.Price"][df_question2["Min.Price"].isna()]

3    NaN
4    NaN
25   NaN
29   NaN
72   NaN
83   NaN
86   NaN
Name: Min.Price, dtype: float64

In [123]:
# generate a summary of min.Price
df_question2["Min.Price"].describe()

count    86.000000
mean     17.118605
std       8.828290
min       6.700000
25%      10.825000
50%      14.600000
75%      20.250000
max      45.400000
Name: Min.Price, dtype: float64

In [122]:
# check the values of nan in max.Price
df_question2["Max.Price"][df_question2["Max.Price"].isna()]

4    NaN
6    NaN
47   NaN
62   NaN
82   NaN
Name: Max.Price, dtype: float64

In [124]:
# generate a summary of max.Price
df_question2["Max.Price"].describe()

count    88.000000
mean     21.459091
std      10.696563
min       7.900000
25%      14.575000
50%      19.150000
75%      24.825000
max      80.000000
Name: Max.Price, dtype: float64

In [130]:
# loc is label-based. 
# You specify row labels and column names exactly as they appear in the DataFrame.
# df.loc[row_labels, column_labels]
df_question2.loc[df_question2["Max.Price"].isna(), "Max.Price"] = max_price_column_mean
df_question2.loc[df_question2["Min.Price"].isna(), "Min.Price"] = min_price_column_mean

In [131]:
# check whether nan is removed
df_question2["Max.Price"][df_question2["Max.Price"].isna()]
df_question2["Min.Price"][df_question2["Min.Price"].isna()]

Series([], Name: Min.Price, dtype: float64)

In [132]:
# generate a summary of columns min.Price and max.Price
df_question2[["Min.Price", "Max.Price"]].describe()

Min.Price  Max.Price
count  93.000000  93.000000
mean   17.118605  21.459091
std     8.485787  10.401836
min     6.700000   7.900000
25%    11.400000  14.900000
50%    14.900000  21.000000
75%    19.900000  24.400000
max    45.400000  80.000000

In [133]:
# check number of null values
df_question2[["Min.Price", "Max.Price"]].isna().value_counts()

Min.Price  Max.Price
False      False        93
Name: count, dtype: int64

## Answer 2-1 (summary)

In [134]:
# final solution
# Replace missing values in Min.Price and Max.Price columns with their respective mean.
df_question2 = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

min_price_mean = df_question2["Min.Price"].mean()
df_question2.loc[df_question2["Min.Price"].isna(), "Min.Price"] = min_price_mean

max_price_mean = df_question1["Max.Price"].mean()
df_question2.loc[df_question2["Max.Price"].isna(), "Max.Price"] = max_price_mean

df_question2[["Min.Price", "Max.Price"]].describe()

Min.Price  Max.Price
count  93.000000  93.000000
mean   17.118605  21.459091
std     8.485787  10.401836
min     6.700000   7.900000
25%    11.400000  14.900000
50%    14.900000  21.000000
75%    19.900000  24.400000
max    45.400000  80.000000

# Question 2-3: 
How to get the rows of a dataframe with row sum > 100?

In [136]:
df_question3 = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [138]:
# generate a snapshot of this dataframe
df_question3.head()

0   1   2   3
0  30  37  27  28
1  11  10  16  10
2  17  31  11  22
3  11  13  25  38
4  33  31  23  30

In [139]:
# study the random number generation part
# 60 random numbers from [10,40]
np.random.randint(10, 40, 60).shape

(60,)

In [140]:
# study this dataframe
df_question3.shape

(15, 4)

In [141]:
# check if dataframe[row, column]
df_question3.iloc[0,3]

28

In [142]:
# generate a new column that sums the row values
df_question3["row_sum"] = df_question3.sum(axis = 1)

In [143]:
# check the result
df_question3.head()

0   1   2   3  row_sum
0  30  37  27  28      122
1  11  10  16  10       47
2  17  31  11  22       81
3  11  13  25  38       87
4  33  31  23  30      117

In [144]:
# filter the rows with row_sum > 100
df_question3[df_question3["row_sum"] > 100]

0   1   2   3  row_sum
0   30  37  27  28      122
4   33  31  23  30      117
11  30  23  30  32      115
13  21  35  27  27      110
14  17  39  20  39      115

## Answer 2-4

In [145]:
# final solution
df_question3 = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df_question3["row_sum"] = df_question3.sum(axis = 1)
df_question3[df_question3["row_sum"] > 100]

0   1   2   3  row_sum
0   29  32  34  24      119
9   19  19  37  34      109
11  22  36  14  32      104
13  10  29  28  35      102